### ISSUE TITLE
MockProvider does not call promise's callback

### ISSUE THREAD

**Issue by daneov** [hyperoslo/Malibu#103]
The following snippet shows a reproducible case in which neither success nor failure on the promise's part is called.

This seems to be in part due to the `Networking` instance being deallocated (the [weak self check](https://github.com/hyperoslo/Malibu/blob/master/Sources/Networking.swift#L155)) returns since it is nil.

How can I work around this?

```Swift
final class MockProviderSpec: QuickSpec {
    override func spec() {
        describe("Test") {
            it("Passes") {
                let fetcher = APIFetcher()
                waitUntil { done in
                    fetcher.request(request: CustomEndpoint.test).then({ _ in
                        done()
                    }).fail({ error in
                        done()
                    })
                }
            }
        }
    }
}

class APIFetcher {
    var mockClosure: ((RequestConvertible) -> Mock?)?

    func defaultClosure(_ request: RequestConvertible) -> Mock?{
        return Mock(json: [:])
    }

    func request(request: CustomEndpoint) -> NetworkPromise {

        let networking = Networking<CustomEndpoint>(mode: .sync, 
                                                    mockProvider: MockProvider<CustomEndpoint>(defaultClosure)
        )
        return networking.request(request)
    }
}

enum CustomEndpoint: RequestConvertible {
    static var baseUrl: URLStringConvertible?

    static var headers: [String : String] = [:]

    var request: Request {
        return Request.post("mock://derp")
    }

    case test
}

**Comment by vadymmarkov** [comment]
You could make `networking` an instance var in your test and then inject it to `APIFetcher` for example.

**Comment by daneov** [comment]
Sorry, due to oversimplifying the real case got lost :)

Here is a [gist](https://gist.github.com/daneov/01b2655fe78a82f084555b2886bdf4c1) containing the actual case.

The `execute<T>(request: T) -> NetworkPromise` is required by the protocol, and relied upon by my services.

If I want to test a service, I thus mock the `APIClient` in them, and the `Networking` instance is configured _in_ the `APIMockClient`, since in the real world, it is also responsible for configuring the `Networking`'s headers and authentication token.

Now, in a real world example this approach works:

```Swift
    func execute<T>(request: T,
                    mockProvider: MockProvider<T>? = nil) -> NetworkPromise where T: RequestConvertible {
        let networking = Networking<T>(mode: .async, mockProvider: mockProvider)
        networking.configureHeaders()
        networking.configure(token: userManager.accessToken)

        return networking.request(request).validate()
```

So I am a bit confused here, as the exact same approach is used.

**Comment by daneov** [comment]
I ended up making sure the `Networking` instance doesn't deallocate in the tests by retaining the object as follows:
```Swift
func execute<T>(request: T,
                    mockProvider: MockProvider<T>? = nil) -> NetworkPromise where T: RequestConvertible {
        let networking = Networking<T>(mode: .async, mockProvider: mockProvider)
        return networking.request(request).validate().always({ _ in _ = networking })
```
Thanks for the help!
