### ISSUE TITLE
Documentation Error for Pre-processing

### ISSUE THREAD

**Issue by placrosse** [hyperoslo/Malibu#106]
Pre-processing

// Use this closure to modify your `Request` value before `URLRequest`
// is created on base of it
networking.beforeEach = { request in
  var request = request
  request.message.parameters["userId"] = "12345"  //  <=== line does not compile, due to both no message on request, and parameters not mutable

  return request
}

**Comment by vadymmarkov** [comment]
Hi @placrosse! You're right. There is a PR that adds a new method to modify requests https://github.com/hyperoslo/Malibu/pull/107. Documentation has also been updated.
