### ISSUE TITLE
No such module Malibu

### ISSUE THREAD

**Issue by onmyway133** [hyperoslo/Malibu#3]
After cloning the project (latest commit 4636674432a6ba50708a44ed11b782d1f60166b2)

- cd into MalibuDemo
- pod install
- open MalibuDemo.xcworkspace

![Alt text](https://monosnap.com/file/8XjbzD70mT0zzZ2qM8lgheo6GUnmQw.png)

**Comment by zenangst** [comment]
@onmyway133 still an issue?

**Comment by onmyway133** [comment]
It is OK now 😄
