### ISSUE TITLE
pod install: Unable to find a specification for `Malibu`

### ISSUE THREAD

**Issue by TheTekton** [hyperoslo/Malibu#38]
Malibu is unavailable on CocoaPods. Until that's sorted, one could use `pod 'Malibu', :git => 'git@github.com:hyperoslo/Malibu.git'` instead of `pod 'Malibu'`, in their Podfile.

**Comment by vadymmarkov** [comment]
@TheTekton Malibu v1.0.0 https://github.com/hyperoslo/Malibu/releases is released on CocoaPods, so we can close this one.
