### ISSUE TITLE
Improve mocks

### ISSUE THREAD

**Issue by zenangst** [hyperoslo/Malibu#46]
I just got an idea for an improvements to mocks. Right now you can mock using static JSON files, which is awesome and super easy to setup. But what if you could mock it by passing a closure so that you could give back computed mocks. I think this could be pretty neat if you combine it with components like `Fakery` (https://github.com/vadymmarkov/Fakery)

What do you guys think? @hyperoslo/ios

**Comment by vadymmarkov** [comment]
@zenangst What about init mock with dictionary: https://github.com/hyperoslo/Malibu#mocks

**Comment by zenangst** [comment]
@vadymmarkov Yeah you could do that but I wanted more dynamic content, so instead of static dictionaries, you could initialize a mock request with a closure. If this sounds familiar, it is because this is essentially what you just told me in person 😁

**Comment by vadymmarkov** [comment]
I think this is an old one that we can close. We've got `MockProvider`, which is more flexible than static dictionaries we had before.
