### ISSUE TITLE
Download progress

### ISSUE THREAD

**Issue by guilhermearaujo** [hyperoslo/Malibu#64]
Is it possible to track the progress/percentage of a file download? If yes, how?

**Comment by ttuygun** [comment]
There're some abstraction library such as Moya or APIKit that has a progress feature. You can read the code and make a pull request that working with Malibu

**Comment by vadymmarkov** [comment]
@guilhermearaujo We haven't had a need for progress feature yet, but as @ttuygun said, feel free to make a PR 😉
