### ISSUE TITLE
Update Dependencies

### ISSUE THREAD

**Issue by bmctigue** [hyperoslo/Malibu#73]
Morning All,
Tried to install the library through cocoapods yesterday and the library won't compile. Seems there are references to updates in the When library which aren't there. Installing through cocoa-odds installs When version 2.1.1 when the changes are at least in the latest version 2.3.3. I updated the pod spec locally and installed When 2.3.3 which fixed the references, but the RequestConvertible isn't running the promise. Using the default promise works, i.e. "let promise = Malibu.request(Request.get("https://api.myjson.com/bins/1bgj27"))", but using the RequestConvertible method doesn't. Didn't want to troubleshoot much without you having a chance to update the dependencies. Hope this makes sense. Let me know if I'm just doing something stupid. Bruce

**Comment by vadymmarkov** [comment]
Hi @bmctigue! Do you use v5.0.0?

**Comment by bmctigue** [comment]
Yes, in my pod file I specified tag 5.0.0

**Comment by bmctigue** [comment]
By the way, all the libraries you guys produce are outstanding. Thanks for the effort!

**Comment by vadymmarkov** [comment]
Thanks @bmctigue. We're always happy to hear such a great feedback. 
Back to the question:
1) `Malibu` 5.0.0 uses `When` 2.3.3, so if for some reason `pod install` fails you can try to do `pod repo update`. 
2) `RequestConvertible` should work if you declare your `enum`, create `Networking` and call `request`, as described here https://github.com/hyperoslo/Malibu#making-a-request

**Comment by bmctigue** [comment]
Ok, i tried all the above yesterday and it didn't work. Did update the repo. I'll try again and add the exact code to the issue. Thanks.

**Comment by bmctigue** [comment]
Hi, okay, the dependencies are fixed. I think I did the pod repo update command and then didn't do the normal pod install again. I was using the local forked repository. No more build errors. Thanks.

**Comment by bmctigue** [comment]
However, `RequestConvertible` still isn't working. Here's the exact code I'm using:
`//
//  Malibu.swift
//  flurri
//
//  Created by Bruce McTigue on 6/18/17.
//  Copyright © 2017 tiguer. All rights reserved.
//

import Foundation
import Malibu

enum FlurriEndpoint: RequestConvertible {
    case event(id: String)
    
    static var baseUrl: URLStringConvertible? = "https://api.myjson.com"
    
    static var headers: [String: String] = [
        "Accept" : "application/json"
    ]
    
    var request: Request {
        switch self {
        case .event(let id):
            return Request.get("bins/\(id)")
        }
    }
}

final class EventNetworkController: NSObject {

    func getMockEvent() {
        
        Malibu.logger.level = .verbose
        
        let networking = Networking<FlurriEndpoint>()
        let networkpromise = networking.request(.event(id:"1bgj27"))
        networkpromise.done({ data in
            print("made it here")
        })
    }
}`
I'm just call getMockEvent from the app delegate. Seems the closure is getting dispatched, but the closure doesn't run. Seems like an issue in the When library. This code from the When library Promise.swift is getting called, I set a breakpoint, but the closure isn't executed. Here's the When relevant code:
`private func dispatch(_ queue: DispatchQueue, closure: @escaping () -> Void) {
    if queue === instantQueue {
      closure()
    } else {
      queue.async(execute: closure)
    }
  }`
queue.async(execute: closure) is getting called. Let me know if I can send something else.

**Comment by vadymmarkov** [comment]
@bmctigue It seems like your networking and promise instances are deallocated. Try to store reference to either networking:
```swift
final class EventNetworkController: NSObject {
  private let networking = Networking<FlurriEndpoint>()

  func getMockEvent() {
    Malibu.logger.level = .verbose
    
    networking.request(.event(id:"1bgj27")).done({ data in
        print("made it here")
    })
}
```

or response promise:
```swift
final class EventNetworkController: NSObject {
  private let networking = Networking<FlurriEndpoint>()
  private var promise: NetworkPromise?

  func getMockEvent() {
    Malibu.logger.level = .verbose
    
    promise = networking.request(.event(id:"1bgj27"))
    promise.done({ data in
        print("made it here")
    })
}
```

**Comment by bmctigue** [comment]
@vadymmarkov, thanks for the reply. Unfortunately, your solution didn't help. I worked with it a little more and found the shared network object is working while the request convertible still isn't. Here's my test code which simply tries to do both and log the results:

```
final class EventNetworkController: NSObject {
    
    private let networking = Networking<FlurriEndpoint>()
    private var notWorkingRequest: NetworkPromise!
    
    func getMockEvent() {
        notWorkingRequest = networking.request(.event(id: "1bgj27"))
        notWorkingRequest.done({ data in
            print("FlurriEndpoint is working")
        })
        
        let workingRequest = Request.get("https://api.myjson.com/bins/1bgj27")
        let promise = Malibu.request(workingRequest)
        promise.done({ data in
            print("")
            print("Shared network object is working")
        })
    }
}
```
Here is the output of the log file, you can see there is only one network request from the logger and one promise output for the shared network object

```
Shared network object is working
🏄 MALIBU: Catching the wave...
GET https://api.myjson.com/bins/1bgj27
Headers:
["Accept-Language": "en;q=1.0"]
Response: 200
```

**Comment by vadymmarkov** [comment]
@bmctigue Hm... What about your `EventNetworkController` instance, do you keep a reference to it or just create somewhere in a method? Try to print something in `deinit`.

**Comment by bmctigue** [comment]
@vadymmarkov good morning. Okay, that works. Sorry for the confusion. Makes sense to me now that we need to keep a reference around for this potentially slow background task. The shared network object also must be referenced from the library and is not deallocated. Thanks for the help!!!

**Comment by vadymmarkov** [comment]
Glad I could help @bmctigue 😉
