### ISSUE TITLE
Can't get the response body if validation fails

### ISSUE THREAD

**Issue by zwolsman** [hyperoslo/Malibu#84]
If the validation fails (let's say the server returns 400> status code) there is no way to get the data that the server returns.

Would be very helpful if there is a way to get the data so you can display server sided exceptions.

**Comment by onmyway133** [comment]
@zwolsman Hi, `Malibu` deals with `Promise`, so you can use `fail` to catch error

```swift
.done({ boards in
    // Handle response data
  })
  .fail({ error in
    // Handle errors
  })
  .always({ _ in
    // Hide progress bar
  })
```

**Comment by zwolsman** [comment]
I saw that, but the problem is. if you have code like this

```swift
.validate(statusCodes: [200]).fail({err in print(err) })
```

The `err` will be `Response status code \(statusCode) was unacceptable`, you are not able to get the response body from the request..

**Comment by vadymmarkov** [comment]
@zwolsman Would it solve your problem if we extend error types with more parameters, like:
```swift
case unacceptableStatusCode(Int, Data, HTTPURLResponse)
case unacceptableContentType(String, Data, HTTPURLResponse)
```

**Comment by zwolsman** [comment]
@vadymmarkov I think that every error that throws (and there is data available) it should contain the data. Maybe a transformer too so you can map your data to your error object.

**Comment by vadymmarkov** [comment]
I agree, we can start with errors. I will look into it 😉

**Comment by vadymmarkov** [comment]
Version 6.1.0 with improved errors is out @zwolsman
