### ISSUE TITLE
Malibu including 'When' in `Malibu.framework/Frameworks` folder

### ISSUE THREAD

**Issue by daneov** [hyperoslo/Malibu#96]
Because of how Malibu is including `When`, using the `copy-frameworks`, it's included in the build result, you end up with the following:

``` 
Malibu.framework
| Malibu (executable)
| Info.plist
| _CodeSignature
| Frameworks
    | When.framework
        |   <contents of When>
```

This, in turn, results in the following rejections in the App Store:

```
Invalid Bundle. The bundle at '<AppName>.app/Frameworks/Malibu.framework' contains disallowed file 'Frameworks.
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.vadymmarkov.When-iOS' under the iOS application '<AppName>.app'
```

I also include the 'When.framework' in my own project.

Any reason you're doing it that way? Am I the first to encounter this? @vadymmarkov

**Comment by vadymmarkov** [comment]
Should be fixed in https://github.com/hyperoslo/Malibu/pull/99
