### ISSUE TITLE
Increased number of errors after updating to 6.3.0+

### ISSUE THREAD

**Issue by guilhermearaujo** [hyperoslo/Malibu#98]
Recently I released two updates of my app with no updates (concerning networking or the requests the app makes, or how and when they are made), but I did update Malibu from 6.2.0 to 6.3.0, and 6.4.0 in the second update.

Since 6.3.0, several customers have been complaining that some contents cannot be load in the app, and send screenshots displaying the error messages I programmed to be displayed when a network request fails for any reason other than 2 cases: Reachability says the device is offline; or the request returns with a 401 status code.

In my tests, I could never reproduce an error, and the worst case I could recreate was to enable the network conditioner with a very poor condition to force a request to time out.

```swift
.fail { error in
  switch error {
  case is UnreachableError: Alert.warn(R.string.alert.unreachable()) // Reachability
  case is Unauthorized: AppNotification.loggedOut.post() // 401
  default:
    Alert.warn("some 'could not load' message")
    if !(error is ApiError) { // ApiError is base for UnreachableError, Unauthorized and some other erros like 404, 500, 503, etc.
      Crashlytics.sharedInstance().recordError(error)
    }
  }
}
```

So I started logging the errors to Crashlytics, but the only data I get from them is:

> NSERROR-DOMAIN: Malibu.NetworkError
> NSERROR-CODE: 8

Is there any important change since 6.2.0? What case of [NetworkError](https://github.com/hyperoslo/Malibu/blob/da4354877909d0f1efa86d642f4739290500ceb4/Sources/NetworkError.swift) is this one whose code is `8`??
How can I debug it better and get more data to understand what's really happening?

This is how the `UnreachableError` is thrown:
```swift
networking.middleware = { promise in
  if let connection = Reachability()?.connection, connection != .none {
    promise.resolve(Void())
  } else {
    promise.reject(UnreachableError())
  }
}
```

**Comment by guilhermearaujo** [comment]
Hi @vadymmarkov,
That does seem to be the problem, however it still seems a bit weird:

Prior to #97, the default behaviour for ETag Policy was `enabled`. This PR changed it to be `disabled`, and my app does not override it.
Therefore, my app requests (using 6.4.0) should never include the ETag header, I suppose, and consequently, the back-end should not respond with 304.

Is this correct or am I missing a point here?

**Comment by vadymmarkov** [comment]
It's hard to say why it isn't failing consistently. You can test ETags by doing the same request multiple times and inspecting the status code. You can also try to clear ETags storage `Malibu.clearStorages()` to start from the clean state.

**Comment by guilhermearaujo** [comment]
Alright then. Things are a bit clearer now, and I sort of know how to investigate it further, I'll close this.
